/*
Problem 2 - Project Euler

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include <iostream>

using namespace std;

int fibonacci(int n1, int n2){
    int current[] = {n1, n2};
    int result, sum = 0;

    while(result < 4000000){
        if (current[0] + current[1] > 4000000){
            break;
        }
        else{
            result = current[0] + current[1];
            current[0] = result;
            if (result%2==0){
                sum+=result;
            }

            result = current[0] + current[1];
            current[1] = result;
            if (result%2==0){
                sum+=result;
            }
        }
    }
    return sum;
}

int main(){
    cout << fibonacci(0, 1);
    return 0;
}